project_id = "kolzaqqfwldrksyrlwxx"

[functions.generate-sitemap]
verify_jwt = false

[functions.send-email-v2]
verify_jwt = false

[functions.test-email-v2]
verify_jwt = true

[functions.optimize-image]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.test-email]
verify_jwt = true
