/**
 * PingPe Brand Configuration
 * Official branding, content, and service data for Jungle Resort Pingpe
 */

export const PINGPE_BRAND = {
  name: "PingPe",
  fullName: "Jungle Resort PingPe",
  tagline: "Experience Authentic Upper Suriname",
  taglineNL: "Beleef tijdens uw tour het authentieke Boven-Suriname!",
  description: "Jungle Resort PingPe offers fully organized tours to the interior of Suriname. During the three to six-day tours, you will be guided by an expert guide who originates from the interior of Upper Suriname.",
  location: {
    resort: "Boven-Suriname River, Suriname",
    address: "Kromme Elleboogstraat 22, Paramaribo",
    coordinates: { lat: 4.5, lng: -55.2 },
  },
  contact: {
    email: "info@jungleresortpingpe.com",
    phone: "+597 123 4567",
    website: "https://www.jungleresortpingpe.com",
  },
  social: {
    facebook: "https://www.facebook.com/jungleresortpingpe",
  },
};

export const PINGPE_TOURS = [
  {
    id: "back-to-basic",
    title: "Back to Basic Tour",
    subtitle: "Authentic jungle experience on the Boven-Suriname River",
    description: "Experience the authentic interior of Suriname during this 3-day tour. Stay at our small-scale resort on the Boven-Suriname River and immerse yourself in Saramaccan culture.",
    duration: "3 days / 2 nights",
    price: 285,
    priceUnit: "person",
    category: "river-tour",
    difficulty: "Easy",
    maxParticipants: 12,
    includes: [
      "Expert local guide from Upper Suriname",
      "All meals and accommodations",
      "River transport by boat",
      "Cultural village visits",
      "Nature walks and swimming",
    ],
    highlights: [
      "Authentic Saramaccan village life",
      "Pristine rainforest environment",
      "River activities and waterfalls",
      "Traditional meals and storytelling",
    ],
  },
  {
    id: "extended-adventure",
    title: "Extended Jungle Adventure",
    subtitle: "Deep dive into Suriname's interior wilderness",
    description: "Our most comprehensive 6-day tour takes you deep into the heart of Suriname's rainforest, with multiple village visits and extended jungle exploration.",
    duration: "6 days / 5 nights",
    price: 520,
    priceUnit: "person",
    category: "jungle-adventure",
    difficulty: "Moderate",
    maxParticipants: 10,
    includes: [
      "Experienced local guides",
      "All meals and lodge accommodations",
      "Boat transfers and land transport",
      "Multiple village visits",
      "Guided jungle treks",
      "Waterfall excursions",
    ],
    highlights: [
      "Multiple Maroon villages",
      "Extensive rainforest exploration",
      "Ananasaberg waterfall visit",
      "Traditional bush medicine lessons",
      "Night wildlife observation",
    ],
  },
  {
    id: "river-hopping",
    title: "River Hopping Tour",
    subtitle: "Multi-lodge experience along the Boven-Suriname",
    description: "Custom tailored tours where you overnight at different locations along the Boven-Suriname River. Fully organized including local guides, meals, accommodations, transport and all activities.",
    duration: "4-5 days customizable",
    price: 380,
    priceUnit: "person",
    category: "river-hopping",
    difficulty: "Easy to Moderate",
    maxParticipants: 8,
    includes: [
      "Multiple lodge stays",
      "Local guide accompaniment",
      "All meals included",
      "River transport between locations",
      "Customizable itinerary",
      "Cultural activities at each stop",
    ],
    highlights: [
      "Experience different river communities",
      "Flexible itinerary options",
      "Varied landscapes and activities",
      "Meet multiple local hosts",
    ],
  },
  {
    id: "day-experience",
    title: "Day Experience at PingPe",
    subtitle: "Quick authentic jungle experience",
    description: "Perfect for travelers with limited time. Experience our resort, enjoy a traditional lunch, swim in the river, and take a short jungle walk.",
    duration: "1 day",
    price: 95,
    priceUnit: "person",
    category: "day-trip",
    difficulty: "Easy",
    maxParticipants: 15,
    includes: [
      "Round-trip transport from Paramaribo",
      "Traditional Surinamese lunch",
      "Guided nature walk",
      "River swimming",
      "Cultural storytelling",
    ],
    highlights: [
      "Perfect for short visits",
      "Traditional meal experience",
      "River and forest activities",
      "Meet local community members",
    ],
  },
];

export const PINGPE_ACCOMMODATIONS = [
  {
    id: "traditional-hut",
    title: "Traditional River Hut",
    subtitle: "Authentic Saramaccan-style accommodation",
    description: "Stay in our traditional wooden huts built in authentic Saramaccan style, directly on the Boven-Suriname River. Basic but comfortable, with mosquito nets and river views.",
    guests: 4,
    bedrooms: 2,
    beds: 4,
    bathrooms: 1,
    price: 75,
    amenities: [
      "River view",
      "Mosquito nets",
      "Shared bathrooms",
      "Solar power",
      "Traditional construction",
    ],
    features: [
      "Authentic experience",
      "Direct river access",
      "Natural ventilation",
      "Community atmosphere",
    ],
  },
  {
    id: "eco-cabin",
    title: "Eco-Comfort Cabin",
    subtitle: "Modern comfort meets nature",
    description: "Our upgraded cabins offer more comfort while maintaining our eco-friendly ethos. Private facilities, better insulation, and comfortable beds.",
    guests: 2,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    price: 95,
    amenities: [
      "Private bathroom",
      "Comfortable mattresses",
      "Screened windows",
      "Porch with hammock",
      "Solar lighting",
    ],
    features: [
      "More privacy",
      "Better comfort",
      "Eco-friendly design",
      "River views",
    ],
  },
];

export const PINGPE_ACTIVITIES = [
  {
    id: "jungle-trek",
    title: "Guided Jungle Trek",
    subtitle: "Explore the pristine rainforest with local experts",
    duration: "3-4 hours",
    price: 35,
    difficulty: "Moderate",
    maxParticipants: 8,
    description: "Trek through virgin rainforest with guides who know every plant, animal, and trail. Learn about medicinal plants and jungle survival.",
  },
  {
    id: "village-visit",
    title: "Cultural Village Visit",
    subtitle: "Experience authentic Saramaccan life",
    duration: "2-3 hours",
    price: 25,
    difficulty: "Easy",
    maxParticipants: 12,
    description: "Visit nearby Saramaccan villages, meet local families, learn about their traditions, and hear their stories.",
  },
  {
    id: "waterfall-excursion",
    title: "Waterfall Swimming Excursion",
    subtitle: "Natural pools and cascading waterfalls",
    duration: "Half day",
    price: 45,
    difficulty: "Moderate",
    maxParticipants: 10,
    description: "Hike to beautiful waterfalls including the famous Ananasaberg, swim in crystal-clear pools.",
  },
  {
    id: "river-kayaking",
    title: "River Kayaking",
    subtitle: "Paddle the Boven-Suriname River",
    duration: "2-3 hours",
    price: 30,
    difficulty: "Easy",
    maxParticipants: 6,
    description: "Explore the river at your own pace, spot wildlife, and enjoy the peaceful water.",
  },
  {
    id: "night-wildlife",
    title: "Night Wildlife Observation",
    subtitle: "Discover nocturnal rainforest creatures",
    duration: "2 hours",
    price: 40,
    difficulty: "Easy",
    maxParticipants: 8,
    description: "Experience the jungle after dark with flashlights, spotting frogs, insects, and night birds.",
  },
];

export const PINGPE_TRANSPORT = [
  {
    id: "paramaribo-atjoni",
    title: "Paramaribo to Atjoni Transfer",
    subtitle: "Comfortable road transfer to the river",
    route: "Paramaribo → Atjoni",
    duration: "4-5 hours",
    price: 45,
    priceUnit: "person",
    vehicleType: "4x4 Van",
    capacity: 8,
    description: "Reliable transport from Paramaribo to Atjoni (river port), where your boat journey begins.",
  },
  {
    id: "river-boat",
    title: "River Boat Transport",
    subtitle: "Scenic boat ride on the Boven-Suriname",
    route: "Atjoni → PingPe Resort",
    duration: "1.5-2 hours",
    price: 35,
    priceUnit: "person",
    vehicleType: "Traditional River Boat",
    capacity: 12,
    description: "Traditional motorized boat transport along the beautiful Boven-Suriname River.",
  },
];

export const PINGPE_PACKAGES = [
  {
    id: "complete-suriname",
    title: "Complete Suriname Experience",
    subtitle: "Interior + Coast + City combo package",
    duration: "9 days / 8 nights",
    price: 1250,
    discount: 15,
    maxParticipants: 8,
    description: "The ultimate Suriname adventure combining our jungle resort stay with coastal experiences and Paramaribo city exploration.",
    includes: [
      "3 nights at PingPe Resort (Back to Basic Tour)",
      "2 nights coastal eco-lodge",
      "2 nights Paramaribo hotel",
      "All transport between locations",
      "All meals during jungle stay",
      "Breakfast in Paramaribo and coast",
      "Guided city tour of Paramaribo",
      "Dolphin watching boat trip",
    ],
  },
  {
    id: "adventure-week",
    title: "Adventure Week Package",
    subtitle: "Action-packed 7 days in the jungle",
    duration: "7 days / 6 nights",
    price: 680,
    discount: 10,
    maxParticipants: 10,
    description: "For adventure seekers: Extended jungle stay with maximum activities and exploration.",
    includes: [
      "6 nights at PingPe Resort",
      "All meals included",
      "Multiple village visits",
      "Waterfall expeditions",
      "Jungle treks",
      "Night wildlife tours",
      "Kayaking and swimming",
      "Transport from/to Paramaribo",
    ],
  },
];

export const PINGPE_SEO = {
  defaultTitle: "Jungle Resort PingPe | Authentic Suriname Tours",
  titleTemplate: "%s | PingPe Suriname",
  description: "Experience authentic Suriname with Jungle Resort PingPe. Eco-friendly jungle tours, cultural experiences, and sustainable tourism in the heart of the Boven-Suriname River region.",
  keywords: [
    "Suriname tours",
    "jungle resort Suriname",
    "eco-tourism Suriname",
    "Boven-Suriname",
    "Saramaccan culture",
    "rainforest tours",
    "sustainable tourism",
    "authentic Suriname",
    "river tours Suriname",
    "jungle lodge",
  ],
  og: {
    siteName: "Jungle Resort PingPe",
    type: "website",
    locale: "en_US",
  },
};
