// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kolzaqqfwldrksyrlwxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbHphcXFmd2xkcmtzeXJsd3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTcxMDgsImV4cCI6MjA3NTc5MzEwOH0.XIbv1yP6LHpDQvJvjY_QOw1DWBHQebygPssUw1wwbvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});